[theme]
#base="dark"
#primaryColor="#27cb70"
#backgroundColor="#59816b"
#secondaryBackgroundColor="#2A7161"


base="light"
primaryColor="#13dcb7"
secondaryBackgroundColor="#C6DCDA"
textColor="#5e5c5c"

